# index:
#    path: /
#    controller: App\Controller\DefaultController::index
#    methods: [GET, POST]

# _errors:
#     resource: '@FrameworkBundle/Resources/config/routing/errors.xml'
#     prefix: /_error